include("overtPoly_helpers.jl")
include("nn_mip_encoding.jl")
include("overtPoly_to_mip.jl")
include("overt_to_pwa.jl")
include("problems.jl")
using LazySets


function encode_dynamics(query::OvertPQuery)
    """
    Method to encode the dynamics as a MIP (using the Gessing et al. method)
    """
    LB, UB = query.problem.bounds
    Tri = OA2PWA(LB)
    #These are the vertices of the triangulation
    xS = [(tup[1:end-1]) for tup in LB]
    yUB = [tup[end] for tup in UB]
    yLB = [tup[end] for tup in LB]

    mipModel = ccEncoding(xS, yLB, yUB, Tri, query)
    return mipModel
end

function encode_control!(query, mipModel)
    """
    Method to encode the controller as a MIP (using the Tjeng et al. method)
    Modifies the MIP model in place
    """
    input_set = query.problem.domain   ###For controller MIP encoding, need model, network address, input set, input variable names, output variable names
    network_file = query.network_file

    #Get dictionary of MIP variables 
    input_vars = query.var_dict[:x]
    control_vars = query.var_dict[:u][1]
    output_vars = query.var_dict[:y][1]

    controller_bound = add_controller_constraints!(mipModel, network_file, input_set, input_vars, control_vars)
end


function reach_solve(mipModel, query, t_idx::Union{Nothing,Int64}=nothing)
    """
    Solve contrete reachability problem using MIP. Given a MIP encoding a pwl overapproximation of the dynamics, as well as MIP for the controlller, find the overapproximation of the reachable set
    """
    lows = Array{Float64}(undef, 0)
    highs = Array{Float64}(undef, 0)
    


    #Account for case where dynamics are timed
    if !isnothing(t_idx)
        input_vars = query.var_dict[Meta.parse("x_$t_idx")]
        control_vars = query.var_dict[Meta.parse("u_$t_idx")][1]
        output_vars = query.var_dict[Meta.parse("y_$t_idx")][1]
        integration_map = query.problem.update_rule(input_vars, control_vars, [output_vars])
    else
        control_vars = query.var_dict[:u][1]
        input_vars = query.var_dict[:x]
        output_vars = query.var_dict[:y][1]
        integration_map = query.problem.update_rule(input_vars, control_vars, [output_vars]) 
    end
    
    timestep_nplus1_vars = GenericAffExpr{Float64,VariableRef}[]
    #####Enter loop here#################
    #Loop over elements of input_vars_last
    for v in input_vars
        dv = integration_map[v]
    
        next_v = v + query.dt*dv
        push!(timestep_nplus1_vars, next_v)
        @objective(mipModel, Min, next_v)
        JuMP.optimize!(mipModel)
        @assert termination_status(mipModel) == MOI.OPTIMAL
        objective_bound(mipModel)
        push!(lows, objective_bound(mipModel))
        @objective(mipModel, Max, next_v)
        JuMP.optimize!(mipModel)
        @assert termination_status(mipModel) == MOI.OPTIMAL
        objective_bound(mipModel)
        push!(highs, objective_bound(mipModel))
    end
    
    reacheable_set = Hyperrectangle(low=lows, high=highs)
    return reacheable_set
end

function concreach!(query::OvertPQuery)
    """
    Method to solve the concrete reachability problem using MIP.
    Modifies the query object in place (specifically the bounds generated by OVERT)
    """
    query.problem.bounds = bound_pend(query.problem)
    query.var_dict = Dict{Symbol,JuMP.Vector{VariableRef}}()
    mipModel = encode_dynamics(query)
    query.var_dict[:u] 
    encode_control!(query, mipModel)

    reachSet =  reach_solve(mipModel, query)
    return reachSet, query.problem.bounds
end


function multi_step_concreach(query::OvertPQuery)
    """
    Method to solve the concrete reachability problem using MIP for multiple time steps.
    """
    input_set = query.problem.domain
    reachSets = [input_set]
    boundSets = []
    
    for i = 1:query.ntime
        t1 = Dates.now()
        reachSet, boundSet = concreach!(query)
        t2 = Dates.now()
        println("Time for step ", i, " is ", t2-t1)
        push!(reachSets, reachSet)
        push!(boundSets, boundSet)
        query.problem.domain = reachSet
    end
    return reachSets, boundSets
end

